name: Maven push script
on: [push]
jobs:
  Maven-push-script:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Maven build
        run: mvn clean install
      - name: Maven package
        run: mvn package
